galaxy_info:
  author: Firas Ben Nacib
  description: Build and run an Oracle 10g XE Docker container with exposed ports and credentials.
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - oracle
    - docker
    - database
    - 10g
    - xe
    - container

dependencies: []
