galaxy_info:
  author: Firas Ben Nacib
  description: Download and prepare an EAR package from a Nexus repository for deployment.
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - nexus
    - java
    - ear
    - deployment
    - artifact
    - unzip

dependencies: []
